FROM node:20-alpine AS builder

WORKDIR /app

ENV NODE_ENV=development

COPY frontend/package*.json ./
RUN npm ci --legacy-peer-deps --include=dev

COPY frontend/ .

RUN npm run build -- --configuration production

FROM nginx:1.27-alpine AS runner

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/frontend/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
